"use client";

import { addDays, eachDayOfInterval, endOfWeek, format, isToday, startOfWeek } from "date-fns";
import { CalendarDays, ChevronLeft, ChevronRight, GripVertical, LayoutGrid, List, Pencil, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { PageHeader } from "@/features/workspace/page-header";
import { QuickCreate } from "@/features/workspace/quick-create";
import { useWorkspace } from "@/features/workspace/workspace-provider";
import { cn } from "@/lib/utils";

type View = "day" | "week" | "month";
const hours = Array.from({ length: 13 }, (_, index) => index + 7);

export function SchedulePage() {
  const [view, setView] = useState<View>("day");
  const [anchor, setAnchor] = useState(new Date());
  const { schedules, updateSchedule, deleteSchedule } = useWorkspace();
  const [editing, setEditing] = useState<ReturnType<typeof useWorkspace>["schedules"][number] | null>(null);
  const week = useMemo(() => eachDayOfInterval({ start: startOfWeek(anchor, { weekStartsOn: 1 }), end: endOfWeek(anchor, { weekStartsOn: 1 }) }), [anchor]);
  const changePeriod = (direction: number) => setAnchor((date) => view === "month" ? addDays(date, direction * 28) : addDays(date, direction * (view === "week" ? 7 : 1)));
  const currentDate = format(anchor, "yyyy-MM-dd");
  const daySchedules = schedules.filter((item) => item.date === currentDate).sort((a, b) => a.startTime.localeCompare(b.startTime));
  return <div className="mx-auto max-w-[1480px] space-y-6"><PageHeader eyebrow="Time, deliberately allocated" title="Schedule" description="Your calendar starts clear. Add, edit, move, or delete your own time blocks." actions={<QuickCreate defaultType="schedule" />} /><Card className="overflow-hidden"><div className="flex flex-col gap-4 border-b p-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={() => changePeriod(-1)} aria-label="Previous period"><ChevronLeft className="size-4" /></Button><Button variant="outline" size="icon" onClick={() => changePeriod(1)} aria-label="Next period"><ChevronRight className="size-4" /></Button><Button variant="ghost" size="sm" onClick={() => setAnchor(new Date())}>Today</Button><h2 className="ml-2 text-sm font-semibold sm:text-base">{view === "day" ? format(anchor, "EEEE, MMMM d") : view === "week" ? `${format(week[0], "MMM d")} – ${format(week[6], "MMM d, yyyy")}` : format(anchor, "MMMM yyyy")}</h2></div><div className="inline-flex rounded-xl bg-[var(--muted)] p-1" aria-label="Calendar view">{([{ id: "day", label: "Day", icon: List }, { id: "week", label: "Week", icon: CalendarDays }, { id: "month", label: "Month", icon: LayoutGrid }] as const).map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setView(item.id)} className={cn("inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition", view === item.id ? "bg-[var(--card)] text-[var(--foreground)] shadow-sm" : "text-[var(--muted-foreground)]")}><Icon className="size-3.5" />{item.label}</button>; })}</div></div>{view === "day" ? <DayTimeline schedules={daySchedules} onDrop={(id) => updateSchedule(id, { date: currentDate })} onEdit={setEditing} onDelete={deleteSchedule} /> : view === "week" ? <WeekView days={week} schedules={schedules} onMove={updateSchedule} /> : <MonthView anchor={anchor} schedules={schedules} onMove={updateSchedule} />}</Card>{editing ? <ScheduleEditor key={editing.id} schedule={editing} onClose={() => setEditing(null)} onSave={(changes) => { updateSchedule(editing.id, changes); setEditing(null); }} /> : null}</div>;
}

function DayTimeline({ schedules, onDrop, onEdit, onDelete }: { schedules: ReturnType<typeof useWorkspace>["schedules"]; onDrop: (id: string) => void; onEdit: (schedule: ReturnType<typeof useWorkspace>["schedules"][number]) => void; onDelete: (scheduleId: string) => void }) {
  const [dragId, setDragId] = useState<string | null>(null);
  return <div className="overflow-x-auto"><div className="min-w-[680px] p-5"><div className="grid grid-cols-[70px_1fr]"><div /> <div className="relative h-14 border-b"><p className="pt-1 text-xs text-[var(--muted-foreground)]">Today’s plan · drop a block anywhere in this canvas to keep it here</p></div>{hours.map((hour) => <><div key={`label-${hour}`} className="h-24 border-r pr-3 text-right text-xs text-[var(--muted-foreground)]">{String(hour).padStart(2, "0")}:00</div><div key={`slot-${hour}`} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragId) onDrop(dragId); setDragId(null); }} className="relative h-24 border-b bg-gradient-to-r from-transparent to-violet-500/[.015]" /> </>)}<div /> <div className="relative -mt-[calc(13*6rem)] h-[1248px]">{schedules.map((schedule) => { const [hour, minutes] = schedule.startTime.split(":").map(Number); const [endHour, endMinutes] = schedule.endTime.split(":").map(Number); const top = ((hour - 7) * 60 + minutes) * 1.6; const height = Math.max(48, ((endHour - hour) * 60 + endMinutes - minutes) * 1.6); return <article key={schedule.id} draggable onDragStart={() => setDragId(schedule.id)} className="absolute left-3 right-4 cursor-grab overflow-hidden rounded-xl border border-white/30 p-3 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md active:cursor-grabbing" style={{ top, height, backgroundColor: `${schedule.color}1c`, borderLeftColor: schedule.color, borderLeftWidth: 3 }}><div className="flex items-start gap-2"><GripVertical className="mt-0.5 size-3.5 shrink-0 text-[var(--muted-foreground)]" /><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{schedule.title}</h3><p className="mt-1 text-xs text-[var(--muted-foreground)]">{schedule.startTime} – {schedule.endTime} · {schedule.category}</p></div><div className="flex shrink-0"><button draggable={false} onClick={() => onEdit(schedule)} className="rounded p-1 hover:bg-white/50" aria-label="Edit schedule"><Pencil className="size-3.5" /></button><button draggable={false} onClick={() => onDelete(schedule.id)} className="rounded p-1 text-rose-600 hover:bg-white/50" aria-label="Delete schedule"><Trash2 className="size-3.5" /></button></div></div></article>; })}</div></div></div></div>;
}

function ScheduleEditor({ schedule, onClose, onSave }: { schedule: ReturnType<typeof useWorkspace>["schedules"][number]; onClose: () => void; onSave: (changes: Partial<Omit<ReturnType<typeof useWorkspace>["schedules"][number], "id">>) => void }) {
  const [title, setTitle] = useState(schedule.title);
  const [date, setDate] = useState(schedule.date);
  const [startTime, setStartTime] = useState(schedule.startTime);
  const [endTime, setEndTime] = useState(schedule.endTime);
  const [category, setCategory] = useState(schedule.category);
  return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent><DialogTitle>Edit schedule block</DialogTitle><DialogDescription>Update the time and details for this part of your day.</DialogDescription><form className="mt-5 space-y-4" onSubmit={(event) => { event.preventDefault(); onSave({ title: title.trim() || "Untitled block", date, startTime, endTime, category: category.trim() || "Personal" }); }}><label className="block text-sm font-medium">Title<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-transparent px-3" /></label><div className="grid grid-cols-3 gap-3"><label className="text-sm font-medium">Date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-transparent px-3 text-sm" /></label><label className="text-sm font-medium">Starts<input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-transparent px-3 text-sm" /></label><label className="text-sm font-medium">Ends<input type="time" value={endTime} onChange={(event) => setEndTime(event.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-transparent px-3 text-sm" /></label></div><label className="block text-sm font-medium">Category<input value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 h-10 w-full rounded-xl border bg-transparent px-3" /></label><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="h-10 rounded-xl px-4 text-sm hover:bg-[var(--muted)]">Cancel</button><button type="submit" className="h-10 rounded-xl bg-[var(--primary)] px-4 text-sm font-medium text-white">Save changes</button></div></form></DialogContent></Dialog>;
}

function WeekView({ days, schedules, onMove }: { days: Date[]; schedules: ReturnType<typeof useWorkspace>["schedules"]; onMove: (id: string, changes: { date: string }) => void }) {
  const [dragId, setDragId] = useState<string | null>(null);
  return <div className="overflow-x-auto"><div className="min-w-[780px]"><div className="grid grid-cols-7 border-b">{days.map((day) => <div key={day.toISOString()} className={cn("border-r p-3 text-center last:border-r-0", isToday(day) && "bg-violet-500/[.04]")}><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[var(--muted-foreground)]">{format(day, "EEE")}</p><p className={cn("mx-auto mt-1 grid size-7 place-items-center rounded-full text-sm font-semibold", isToday(day) && "bg-[var(--primary)] text-white")}>{format(day, "d")}</p></div>)}</div><div className="grid min-h-[590px] grid-cols-7">{days.map((day) => { const dayKey = format(day, "yyyy-MM-dd"); return <div key={dayKey} className="border-r p-2 last:border-r-0" onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragId) onMove(dragId, { date: dayKey }); setDragId(null); }}>{schedules.filter((item) => item.date === dayKey).sort((a, b) => a.startTime.localeCompare(b.startTime)).map((schedule) => <article key={schedule.id} draggable onDragStart={() => setDragId(schedule.id)} className="mb-2 cursor-grab rounded-lg border-l-[3px] px-2.5 py-2 text-xs transition hover:shadow-sm active:cursor-grabbing" style={{ borderLeftColor: schedule.color, backgroundColor: `${schedule.color}13` }}><p className="font-semibold">{schedule.title}</p><p className="mt-1 text-[10px] text-[var(--muted-foreground)]">{schedule.startTime}</p></article>)}</div>; })}</div></div></div>;
}

function MonthView({ anchor, schedules, onMove }: { anchor: Date; schedules: ReturnType<typeof useWorkspace>["schedules"]; onMove: (id: string, changes: { date: string }) => void }) {
  const [dragId, setDragId] = useState<string | null>(null);
  const start = startOfWeek(new Date(anchor.getFullYear(), anchor.getMonth(), 1), { weekStartsOn: 1 });
  const days = Array.from({ length: 35 }, (_, index) => addDays(start, index));
  return <div className="overflow-x-auto"><div className="min-w-[780px]"><div className="grid grid-cols-7 border-b">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div key={day} className="p-2 text-center text-[11px] font-bold uppercase tracking-[.12em] text-[var(--muted-foreground)]">{day}</div>)}</div><div className="grid grid-cols-7">{days.map((day) => { const key = format(day, "yyyy-MM-dd"); const inMonth = day.getMonth() === anchor.getMonth(); return <div key={key} className={cn("min-h-32 border-b border-r p-2 last:border-r-0", !inMonth && "bg-[var(--muted)]/30")} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragId) onMove(dragId, { date: key }); setDragId(null); }}><p className={cn("mb-2 grid size-6 place-items-center rounded-full text-xs", isToday(day) && "bg-[var(--primary)] font-semibold text-white", !inMonth && "text-[var(--muted-foreground)]")}>{format(day, "d")}</p>{schedules.filter((item) => item.date === key).slice(0, 3).map((schedule) => <article draggable onDragStart={() => setDragId(schedule.id)} key={schedule.id} className="mb-1 cursor-grab truncate rounded-md px-1.5 py-1 text-[10px] font-medium" style={{ color: schedule.color, backgroundColor: `${schedule.color}16` }}>{schedule.startTime} {schedule.title}</article>)}</div>; })}</div></div></div>;
}
